增加百度云内容审核
RockChinQ/QChatGPT pull request #212
Opened 2023-03-04 13:04 UTC by Haibersut

#210

2023-03-04 16:18 UTC, RockChinQ requested changes

2023-03-04 16:18 UTC, RockChinQ commented on config-template.py
> +illgalmessage = "[百度云]请珍惜机器人，当前返回内容不合规"
这里改成`inappropriate_message_tips`吧

2023-03-04 16:18 UTC, RockChinQ commented on pkg/qqbot/filter.py
> +from config import baidu_check, baidu_api_key, baidu_secret_key, illgalmessage
这里字段名也改一下；  
然后不要在文件头引入，因为从老版本升级上来的用户没有这些字段，会直接报错。

2023-03-04 16:18 UTC, RockChinQ commented on pkg/qqbot/filter.py
> +            + get_access_token()
这俩字段都放到ReplyFilter类里，因为必须检查`config.py`中存在这几个字段才使用

2023-03-04 16:18 UTC, RockChinQ commented on pkg/qqbot/filter.py
>          self.sensitive_words = sensitive_words
__init__中用hasattr检查一下config模块是否包含那几个字段，没有的话标记一个变量，之后process里都不用baidu的接口

2023-03-04 17:19 UTC, Haibersut commented on pkg/qqbot/filter.py
> +from config import baidu_check, baidu_api_key, baidu_secret_key, illgalmessage
引入`import importlib`库读取config文件，设定默认值

```
# 默认值( 兼容性考虑 )

baidu_check = False
baidu_api_key = ""
baidu_secret_key = ""
inappropriate_message_tips = "[百度云]请珍惜机器人，当前返回内容不合规"

# 初始化

config = importlib.import_module('config')
baidu_check = config.baidu_check
baidu_api_key = config.baidu_api_key
baidu_secret_key = config.baidu_secret_key
inappropriate_message_tips = config.inappropriate_message_tips
```

2023-03-04 17:22 UTC, Haibersut commented on pkg/qqbot/filter.py
>          self.sensitive_words = sensitive_words
~~虽说之前做了if判断~~
用了hasattr
```
if hasattr(config, 'baidu_check') and hasattr(config, 'baidu_api_key') and hasattr(config, 'baidu_secret_key'):
            self.baidu_check = config.baidu_check
            self.baidu_api_key = config.baidu_api_key
            self.baidu_secret_key = config.baidu_secret_key
```

2023-03-04 17:22 UTC, Haibersut commented on config-template.py
> +illgalmessage = "[百度云]请珍惜机器人，当前返回内容不合规"
已改

2023-03-04 17:23 UTC, Haibersut commented on pkg/qqbot/filter.py
> +            + get_access_token()
干掉了get_access_token，弄在一起了

```
# 百度云审核URL
            baidu_url = "https://aip.baidubce.com/rest/2.0/solution/v1/text_censor/v2/user_defined?access_token=" + \
                str(requests.post("https://aip.baidubce.com/oauth/2.0/token", 
                      params={"grant_type": "client_credentials", 
                              "client_id": baidu_api_key,
                              "client_secret": baidu_secret_key}).json().get("access_token"))
```

2023-03-05 01:49 UTC, RockChinQ requested changes

2023-03-05 01:49 UTC, RockChinQ commented on pkg/qqbot/filter.py
> +inappropriate_message_tips = config.inappropriate_message_tips
这样还是不行啊，你得测试一下，当config.py中不存在这几个变量的时候是否能正常启动；现在这样写，当import此模块的时候，若config.py不存在那几个变量，就会直接import失败；默认值直接放到类里面去，初始化在__init__方法判断这几个字段存在后再进行初始化

2023-03-05 01:55 UTC, RockChinQ commented on pkg/qqbot/filter.py
> +inappropriate_message_tips = config.inappropriate_message_tips
已修复

2023-03-05 02:12 UTC, RockChinQ approved these changes

2023-03-05 02:13 UTC, merged

2023-03-05 02:13 UTC, RockChinQ commented
已合并，感谢贡献！