修改自定义提示语
RockChinQ/QChatGPT pull request #356
Opened 2023-03-31 17:21 UTC by 2675hujilo

## 概述

实现/解决/优化的内容: 

### 事务

- 已阅读仓库[贡献指引](../CONTRIBUTING.md)
-  已与维护者在issues或其他平台沟通此PR大致内容

## 以下内容可在起草PR后、合并PR前逐步完成

### 功能

- [ ] 已编写完善的配置文件字段说明（若有新增）
- [ ] 已编写面向用户的新功能说明（若有必要）
- [ ] 已测试新功能或更改

### 兼容性

- [ ] 已处理版本兼容性
- [ ] 已处理插件兼容问题

### 风险

可能导致或已知的问题:

2023-04-01 01:45 UTC, RockChinQ requested changes

2023-04-01 01:45 UTC, RockChinQ commented on pkg/qqbot/command.py
> +            reply = [format(e)]
这个语句测试过吗，没有看到format函数声明

2023-04-01 01:45 UTC, RockChinQ commented on tips_custom.py
不要让程序直接读取被git跟踪的文件作为配置文件，请独立一个`tips-custom-template.py`，让程序在启动时复制`tips-custom-template.py`到`tips-custom.py`（参考`main.py`的`check_file()`函数），再让程序import这个配置文件。

模板的语言风格还是改为之前的严谨准确的语言吧，你自定义的时候再改为你使用的语言风格。

2023-04-01 01:45 UTC, RockChinQ commented on tips_custom.py
> +biu~biu~biu~""".format(config.session_expire_time // 60)
这里字符串内已经删了`{}`了，为何仍保留format

2023-04-01 01:45 UTC, RockChinQ commented on pkg/qqbot/cmds/mgr.py
> +                raise CommandPrivilegeError(tips_custom.command_admin_message)
这里直接调用tips_custom的字段，不使用format向其中传入原有的`path`参数，会报错信息不明确。后面的字段也是同样的问题，请考虑如何在支持输出消息自定义的同时仍然支持传入参数进行格式化。

2023-04-01 01:45 UTC, RockChinQ commented on pkg/qqbot/manager.py
> +                    reply = tips_custom.reply_message
reply需要的是list类型的数值，这里变成str了

2023-04-01 01:45 UTC, RockChinQ commented on pkg/qqbot/manager.py
> +                replys = tips_custom.replys_message
同

2023-04-01 01:45 UTC, RockChinQ commented on pkg/qqbot/cmds/mgr.py
> +            raise CommandPrivilegeError(tips_custom.command_err_message)
同上

2023-04-01 01:45 UTC, RockChinQ commented on config-template.py
>  hide_exce_info_to_user = False
这个字段和下方`alter_tip_message`字段相关，请在此字段的说明中指引一下可以到何处自定义提示消息

2023-04-01 06:57 UTC, 2675hujilo commented on pkg/qqbot/command.py
> +            reply = [format(e)]
![image](https://user-images.githubusercontent.com/113016971/229270832-4482af8a-a286-4d1f-a435-e201cccf38bc.png)
已测，正常运行。

2023-04-02 08:11 UTC, RockChinQ commented
若已解决请求的更改，请点击评论下方的按钮标记为`Resolved`

2023-04-03 14:42 UTC, RockChinQ commented
## Todo

- [ ] 将 #372 的更改适配此项

2023-04-07 08:05 UTC, RockChinQ approved these changes

2023-04-07 08:35 UTC, RockChinQ commented
即将合并，请不要再提交。若还需要进行更改，请等待此分支合并到`customizable-tips`分支以及`customizable-tips`分支合并到`master`分支之后再提出pr

2023-04-07 08:43 UTC, merged

2023-04-07 08:44 UTC, RockChinQ commented
已合并，感谢贡献！